name: Run ICON-2I script

on:
  schedule:
    # 03:30 UTC tutti i giorni
    - cron: "30 3 * * *"
    # 14:30 UTC tutti i giorni
    - cron: "30 14 * * *"
  workflow_dispatch:  # possibilità di lanciarlo a mano

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps for eccodes
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes0 libeccodes-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Run ICON-2I script with retries
        env:
          RUN: ""
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          DRIVE_FOLDER_ID_ICON2I: ${{ secrets.DRIVE_FOLDER_ID_ICON2I }}
        run: |
          max_retries=5
          attempt=1
          while [ $attempt -le $max_retries ]; do
            echo "Tentativo $attempt di $max_retries"
            if python main.py; then
              echo "Script completato con successo al tentativo $attempt"
              exit 0
            else
              echo "Errore al tentativo $attempt"
              if [ $attempt -lt $max_retries ]; then
                echo "Attendo 30 minuti prima del prossimo retry..."
                sleep 1800
              fi
            fi
            attempt=$((attempt+1))
          done
          echo "Script fallito dopo $max_retries tentativi"
          exit 1
